<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>c6453bd9-e3ac-4281-b328-d3f610dfefb0</UserSecretsId>
  </PropertyGroup>



  <ItemGroup>
    <PackageReference Include="Azure.Extensions.AspNetCore.DataProtection.Blobs" Version="1.5.4" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Catteria.Application\Catteria.Application.csproj" />
    <ProjectReference Include="..\Catteria.Infraestructure\Catteria.Infraestructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Products\" />
  </ItemGroup>



</Project>
